# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CovidPass' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CovidPass
  pod 'Parse'
  pod 'AlamofireImage'
  pod 'MBProgressHUD'
  pod 'MessageInputBar'
  pod 'QRCode'

  target 'CovidPassTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CovidPassUITests' do
    # Pods for testing
  end

end
